CREATE TABLESPACE  TS_BDP4_2018
DATAFILE  'C:\BD\TS_BDP6_2018.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_PRATICA04
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_BDP4_2018
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_BDP4_2018;

GRANT DBA TO USER_PRATICA06 WITH ADMIN OPTION;